language: go
go:
  - 1.9.x
install:
  - go get github.com/tsoding/snitch
  - go get -v .
  - go get -v github.com/golang/lint/golint
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go build -v .
